### ISSUE TITLE
Train with newer danbooru dataset & larger resnets 

### ISSUE THREAD

**Issue by ghost** [RF5/danbooru-pretrained#6]
Do you have any plans to train with newer danbooru dataset & larger resnets?

**Comment by RF5** [comment]
Hi @talent-less , I really wish I could, but I do not have the computing resource to be able to retrain the newer models with the newer datasets. This model I trained with some AWS credits I won from a competition, and they have long since been exhausted. 

If I one day come across enough good fortune on the compute & storage side, I will definitely train and release newer models (like xresnet and resnext) trained on the more recent danbooru datasets.
